name: pet_parent
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.0
  icons_launcher: ^2.1.7
  intl: ^0.18.1
  sqflite: ^2.3.3
  syncfusion_flutter_calendar: ^25.1.40

  path: any
  get: ^4.6.6
  provider: ^6.1.2
  firebase_storage: ^11.7.7
  path_provider: ^2.1.4
  image_picker: ^1.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#E1F1F2"
  image: assets/images/pp_logo.png

icons_launcher:
  image_path: "assets/images/pp_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

