// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzFjPJupUnODC8nQ41B2WdKRk0drXXM4',
    appId: '1:1089666710990:web:7ebbdf2de7a744a20fff9f',
    messagingSenderId: '1089666710990',
    projectId: 'pet-parent-db',
    authDomain: 'pet-parent-db.firebaseapp.com',
    storageBucket: 'pet-parent-db.appspot.com',
    measurementId: 'G-JYJPG4LTT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICHMDN5gFP8OkbfZuN3JedPdaIXWsaQo',
    appId: '1:1089666710990:android:24b16db0f5caa6090fff9f',
    messagingSenderId: '1089666710990',
    projectId: 'pet-parent-db',
    storageBucket: 'pet-parent-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5sLqrZS8JPrXMpoAka2g0TK9vC3Nr60',
    appId: '1:1089666710990:ios:492b3f3a600024f10fff9f',
    messagingSenderId: '1089666710990',
    projectId: 'pet-parent-db',
    storageBucket: 'pet-parent-db.appspot.com',
    iosBundleId: 'com.example.petParent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANzFjPJupUnODC8nQ41B2WdKRk0drXXM4',
    appId: '1:1089666710990:web:b369c0325778d2860fff9f',
    messagingSenderId: '1089666710990',
    projectId: 'pet-parent-db',
    authDomain: 'pet-parent-db.firebaseapp.com',
    storageBucket: 'pet-parent-db.appspot.com',
    measurementId: 'G-RZCPSMW87P',
  );
}
